### ISSUE TITLE
Insert a comma where data is to allow it to load as csv

### ISSUE THREAD

**Issue by ghost** [qarmin/Qarminer#26]
Thank you for this project! Is really great. 

I have one this one suggestion to optionally insert comma to separate the data so this can be loaded as csv to allow for further fine tuning using spreadsheet functionality such as creating average, removing duplicates, filtering etc. 

This is a simple fix with an optional setting adds , in specific areas so data can be extracted. 

timer.txt
132, us - MixinScript.insert_mixin

memory_usage.txt
Before: MixinScript.set_mixin, 289.258728, MB

The string is not a problem since you can do all kinds of string manipulation. The problem is mostly numbers individually which need to be extracted from the rest of the string.

**Comment by ghost** [comment]
In fact I have already done this by manually inserting commas in the specific areas in the script save to file statements but I think as general purpose setting may be useful to others as well. 

Now as I write this I realize I can already open it without , by using space as a delimiter :)

**Comment by qarmin** [comment]
Fixed by https://github.com/qarmin/Qarminer/commit/6daff5763426e692fa606a6afd71a75c47df89ba
